import test from 'node:test';
import assert from 'node:assert/strict';
import {createHashIntelligence} from '../src/cloud/intelligence.js';
const key='fixture-'+ 'x'.repeat(32),hash='a'.repeat(64),now=Date.now();
const response=(extra={})=>new Response(JSON.stringify({data:{id:hash,type:'file',attributes:{last_analysis_stats:{malicious:5,suspicious:1,harmless:10,undetected:2},last_analysis_date:Math.floor(now/1000),...extra}}}));
test('hash connector uses a fixed GET endpoint, no redirects or sample upload',async()=>{let calls=0;const fn=createHashIntelligence({key,now:()=>now,fetcher:async(url,options)=>{calls++;assert.equal(url,'https://www.virustotal.com/api/v3/files/'+hash);assert.equal(options.method,'GET');assert.equal(options.redirect,'error');assert.equal(options.headers['x-apikey'],key);assert.equal(options.body,undefined);return response();}});await assert.rejects(fn('http://evil.invalid'),/HASH_INVALID/);const result=await fn(hash);assert.equal(result.malicious,5);assert(!JSON.stringify(result).includes(key));for(let n=0;n<3;n++)await fn(hash);await assert.rejects(fn(hash),/PROVIDER_RATE_LIMIT/);assert.equal(calls,4);});
test('unknown, credential failures, stale and malformed reports are distinct',async()=>{assert.equal((await createHashIntelligence({key,fetcher:async()=>new Response('',{status:404})})(hash)).state,'unknown');await assert.rejects(createHashIntelligence({key,fetcher:async()=>new Response('',{status:401})})(hash),/PROVIDER_UNAVAILABLE/);for(const attributes of [{last_analysis_date:Math.floor(now/1000)-31*86400},{last_analysis_date:Math.floor(now/1000)+600},{last_analysis_stats:{malicious:-1,suspicious:0,harmless:0,undetected:0}}])await assert.rejects(createHashIntelligence({key,now:()=>now,fetcher:async()=>response(attributes)})(hash));await assert.rejects(createHashIntelligence({key,fetcher:async()=>new Response(JSON.stringify({data:{id:'b'.repeat(64),type:'file'}}))})(hash),/PROVIDER_IDENTITY/);await assert.rejects(createHashIntelligence({key,fetcher:async()=>new Response('x'.repeat(262145))})(hash),/PROVIDER_SIZE/);assert.equal(createHashIntelligence({key:'bad'}),undefined);});

test('rolling quota blocks minute-boundary bursts and rejects array coercion',async()=>{let at=now,calls=0;const fn=createHashIntelligence({key,now:()=>at,fetcher:async()=>{calls++;return response();}});await assert.rejects(fn([hash]),/HASH_INVALID/);await fn(hash);at+=59999;for(let n=0;n<3;n++)await fn(hash);await assert.rejects(fn(hash),/PROVIDER_RATE_LIMIT/);at+=1;await fn(hash);await assert.rejects(fn(hash),/PROVIDER_RATE_LIMIT/);assert.equal(calls,5);});
