import { dashboardTheme } from './dashboard-theme.js';
const escapeHtml = value => String(value ?? '').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#39;');
const labels = {ok:'正常',warning:'警告',finding:'发现风险',unavailable:'等待数据',stale:'数据过期',healthy:'在线',unreachable:'无法连接',unhealthy:'异常',unknown:'未知',unconfigured:'未配置',matched:'完整',changed:'已篡改',active:'正常',staged:'轮换中',expiring:'即将过期',expired:'已过期','not-enrolled':'未注册',partial:'待完成',ready:'身份已就绪','identity-created':'身份已创建','waiting-first-report':'等待首次上报',connected:'已认证连接','attention-required':'需要处理','license-center':'授权中心','build-center':'打包中心',reader:'只读管理员'};
const label = value => labels[value] ?? String(value ?? '未知');
const tone = value => ['ok','healthy','matched','active','connected','ready','identity-created'].includes(value) ? 'ok' : ['warning','staged','expiring','stale','partial','waiting-first-report'].includes(value) ? 'warning' : ['finding','changed','expired','attention-required'].includes(value) ? 'danger' : 'muted';
const badge = value => '<span class="badge '+tone(value)+'">'+escapeHtml(label(value))+'</span>';
const time = value => value ? escapeHtml(value) : '—';
const iconPaths={overview:'M3 3h7v7H3zM14 3h7v7h-7zM3 14h7v7H3zM14 14h7v7h-7z',nodes:'M3 4h18v12H3zM8 21h8M12 16v5',virus:'M12 3v3M12 18v3M3 12h3M18 12h3M5.6 5.6l2.1 2.1M16.3 16.3l2.1 2.1M18.4 5.6l-2.1 2.1M7.7 16.3l-2.1 2.1M17 12a5 5 0 1 1-10 0 5 5 0 0 1 10 0',policy:'M4 6h16M4 12h16M4 18h16M8 3v6M16 9v6M10 15v6',baseline:'M12 3l9 5-9 5-9-5 9-5zM3 12l9 5 9-5M3 16l9 5 9-5',updates:'M12 16V3M7 8l5-5 5 5M4 15v6h16v-6',events:'M6 3h12v18H6zM9 7h6M9 11h6M9 15h4',connection:'M8 10V7a4 4 0 0 1 8 0v3M5 10h14v11H5zM12 14v3'};
const icon=name=>'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="'+iconPaths[name]+'"/></svg>';
const core="<svg class=\"core-svg\" viewBox=\"0 0 440 380\" fill=\"none\" xmlns=\"http://www.w3.org/2000/svg\"><defs><linearGradient id=\"core-top\" x1=\"150\" y1=\"90\" x2=\"300\" y2=\"160\" gradientUnits=\"userSpaceOnUse\"><stop stop-color=\"#b8e6ed\"/><stop offset=\".5\" stop-color=\"#7b91ca\"/><stop offset=\"1\" stop-color=\"#42497f\"/></linearGradient><linearGradient id=\"core-left\" x1=\"135\" y1=\"170\" x2=\"220\" y2=\"280\" gradientUnits=\"userSpaceOnUse\"><stop stop-color=\"#65749a\"/><stop offset=\"1\" stop-color=\"#14243d\"/></linearGradient><linearGradient id=\"core-right\" x1=\"220\" y1=\"180\" x2=\"315\" y2=\"260\" gradientUnits=\"userSpaceOnUse\"><stop stop-color=\"#232d5c\"/><stop offset=\"1\" stop-color=\"#424f8e\"/></linearGradient><radialGradient id=\"core-aura\"><stop stop-color=\"#64b4dc\" stop-opacity=\".23\"/><stop offset=\"1\" stop-color=\"#688ee9\" stop-opacity=\"0\"/></radialGradient></defs><circle cx=\"220\" cy=\"195\" r=\"165\" fill=\"url(#core-aura)\"/><ellipse cx=\"220\" cy=\"278\" rx=\"171\" ry=\"53\" stroke=\"#85a4d1\" stroke-opacity=\".14\"/><ellipse cx=\"220\" cy=\"278\" rx=\"141\" ry=\"39\" stroke=\"#57d7d3\" stroke-opacity=\".45\" stroke-dasharray=\"130 70 30 80\"/><path d=\"M49 210 220 306 391 210M81 173l139 81 139-81\" stroke=\"#809ecf\" stroke-opacity=\".18\"/><path d=\"m220 101 91 52-91 52-91-52 91-52Z\" fill=\"url(#core-top)\" stroke=\"#c3e0ef\" stroke-opacity=\".7\"/><path d=\"m129 153 91 52v105l-91-52V153Z\" fill=\"url(#core-left)\" stroke=\"#81a8c7\" stroke-opacity=\".4\"/><path d=\"m220 205 91-52v105l-91 52V205Z\" fill=\"url(#core-right)\" stroke=\"#748acc\" stroke-opacity=\".5\"/><path d=\"m220 123 54 31-54 31-54-31 54-31Z\" fill=\"#14233e\" stroke=\"#a2d1e5\"/><path d=\"m220 135 31 18-31 18-31-18 31-18Z\" fill=\"#6ee0df\" fill-opacity=\".28\" stroke=\"#a4f6ee\"/><path d=\"m180 196 22 12v67l-22-12v-67Zm60 12 22-12v67l-22 12v-67Z\" fill=\"#3dc9d4\" fill-opacity=\".5\"/><path d=\"M220 76v-28M100 146l-28-16M340 146l28-16M220 321v20\" stroke=\"#64d4d3\" stroke-opacity=\".6\"/><circle cx=\"220\" cy=\"44\" r=\"4\" fill=\"#96e5da\"/><circle cx=\"69\" cy=\"128\" r=\"3\" fill=\"#96e5da\"/><circle cx=\"371\" cy=\"128\" r=\"3\" fill=\"#8e99e7\"/><circle cx=\"220\" cy=\"345\" r=\"3\" fill=\"#96e5da\"/><path d=\"m220 84 107 62v121l-107 62-107-62V146l107-62Z\" stroke=\"#b4d3f6\" stroke-opacity=\".15\" stroke-dasharray=\"6 9\"/></svg>";
export function renderDashboard({status,identities,policy,preview=false}) {
 const nodesMap=status.nodes??{};
 const rules=status.rules??{state:'missing'};
 const ruleReady=rules.state==='ready';
 const ruleVersion=ruleReady?escapeHtml(rules.version):'—';
 const ruleCount=ruleReady?escapeHtml(rules.indicators):'—';
 const ruleExpiry=ruleReady?escapeHtml(new Date(rules.expires_at*1000).toISOString()):'尚无有效规则';
 const ruleCard='<article class="card release-card"><div class="release-icon">'+icon('virus')+'</div><p class="eyebrow">SIGNED HASH INDICATORS</p><h3>签名恶意文件规则</h3><p>铁幕主动拉取；本地验签并保留防回退记录。</p><dl class="details"><div><dt>规则版本</dt><dd>'+ruleVersion+'</dd></div><div><dt>发布序号</dt><dd>'+(ruleReady?escapeHtml(rules.sequence):'—')+'</dd></div><div><dt>哈希特征</dt><dd>'+ruleCount+'</dd></div><div><dt>有效期限</dt><dd>'+ruleExpiry+'</dd></div></dl><span class="badge '+(ruleReady?'ok':'muted')+'">'+(ruleReady?'签名已核验':'等待有效签名包')+'</span></article>';
 const release=status.releases??{state:'missing'};
 const releaseReady=release.state==='ready';
 const releaseCard='<article class="card release-card"><div class="release-icon">'+icon('updates')+'</div><p class="eyebrow">VERIFIED APPLICATION RELEASE</p><h3>铁幕安全程序</h3><p>终端加密拉取，独立验签后由本机管理员升级。</p><dl class="details"><div><dt>最新发布</dt><dd>'+(releaseReady?'v'+escapeHtml(release.version):'—')+'</dd></div><div><dt>验签状态</dt><dd>'+(releaseReady?'发布签名已核验':release.state==='unavailable'?'缓存异常，暂停分发':'等待正式签名包')+'</dd></div><div><dt>激活方式</dt><dd>铁幕 Linux 菜单</dd></div></dl><span class="badge '+(releaseReady?'ok':'muted')+'">'+(releaseReady?'可安全拉取':'等待可用程序包')+'</span></article>';
 const requiredRoles=status.deployment?.required_roles??['license-center','build-center'];
 const configured=status.deployment?.configured_roles??Object.keys(nodesMap);
 const connected=status.deployment?.connected_roles??[];
 const fullyConnected=requiredRoles.every(role=>connected.includes(role));
 const summary=Object.keys(nodesMap).length ? badge(status.summary_state) : '<span class="badge muted">等待终端接入</span>';
 const nodeCards=requiredRoles.map(name=>{const n=nodesMap[name]; if(!n)return '<article class="card node-card"><div class="card-head"><div class="node-icon">'+icon('nodes')+'</div>'+badge('not-enrolled')+'</div><h3>'+escapeHtml(label(name))+'</h3><p>铁幕安全 · 受保护终端</p><div class="empty-node">等待在 Linux 管理菜单中注册</div><div class="node-meta"><span>文件完整性 <b>—</b></span><span>环境检查 <b>—</b></span></div><a class="text-link" href="#connection">配置加密对接 <span>↗</span></a></article>'; return '<article class="card node-card"><div class="card-head"><div class="node-icon">'+icon('nodes')+'</div>'+badge(n.pairing_state)+'</div><h3>'+escapeHtml(label(name))+'</h3><p>铁幕安全 · 受保护终端</p><div class="node-meta"><span>公网探测 '+badge(n.probe?.state)+'</span><span>文件完整性 '+badge(n.integrity?.state)+'</span><span>宿主环境 '+badge(n.host_scan?.state)+'</span><span>报告新鲜度 '+badge(n.report_fresh?'ok':'stale')+'</span></div><dl class="details"><div><dt>最后报告</dt><dd>'+time(n.last_report_at)+'</dd></div><div><dt>可信基线</dt><dd>'+escapeHtml(n.baseline_files)+' 个文件</dd></div></dl><p class="next">'+escapeHtml(n.recommended_action)+'</p></article>';}).join('');
 const roleRows=Object.entries(identities.roles??{}).map(([name,r])=>'<div class="identity-row"><div><strong>'+escapeHtml(label(name))+'</strong><small>'+escapeHtml(r.identity_count)+' 个身份 · 到期 '+time(r.certificate_not_after)+'</small></div><div>'+badge(r.rotation_state)+' '+badge(r.certificate_state)+'</div></div>').join('')||'<div class="empty-state">尚无身份数据</div>';
 const eventRows=(status.events??[]).map(e=>'<li><span class="event-dot '+tone(String(e.kind).includes('warning')?'warning':String(e.kind).includes('resumed')?'ok':'finding')+'"></span><div><strong>'+escapeHtml(e.kind)+'</strong><p>'+escapeHtml(label(e.node))+' · '+escapeHtml(typeof e.details==='string'?e.details:JSON.stringify(e.details))+'</p></div><time>'+time(e.at)+'</time></li>').join('')||'<li class="empty-state"><div class="empty-symbol">'+icon('events')+'</div><strong>暂无安全事件</strong><p>终端接入后，认证、完整性变化与告警会出现在这里。</p></li>';
 const guideSteps=[{done:!preview,title:preview?'云端服务待部署':'云端服务已安装',detail:preview?'当前为本地界面预览，尚未连接实际云端服务。':'安全中心正在运行，网页只读监测可用。'},...requiredRoles.map(role=>({done:configured.includes(role),title:configured.includes(role)?label(role)+'已注册':'注册'+label(role),detail:'创建专属证书与独立令牌，保留角色隔离。'})),{done:fullyConnected,title:fullyConnected?'监测连接已完成':'完成监测连接',detail:fullyConnected?'两个业务角色均已通过 mTLS 认证并开始上报。':'等待业务节点通过认证并提交首次有效报告。'}];
 const firstPending=guideSteps.findIndex(s=>!s.done);
 const guide=guideSteps.map((s,i)=>'<li class="guide-step '+(s.done?'done':i===firstPending?'current':'')+'"><span>'+ (s.done?'✓':String(i+1).padStart(2,'0'))+'</span><div><strong>'+escapeHtml(s.title)+'</strong><p>'+escapeHtml(s.detail)+'</p></div><em>'+ (s.done?'已完成':i===firstPending?'当前步骤':'待完成')+'</em></li>').join('');
 const nextAction=fullyConnected?'首次对接已完成。定期检查上报新鲜度、证书和告警。':'在安全服务器运行 sudo appgog-security，选择 1“首次配置向导”，再将身份包导入对应业务节点。';
 const nav=[['overview','安全总览'],['nodes','铁幕终端'],['virus','病毒库中心'],['policy','查杀与策略'],['baseline','可信基线'],['updates','更新发布'],['events','安全事件'],['connection','加密对接']].map(([id,title],i)=>(i===2?'<p class="nav-group">安全能力</p>':i===6?'<p class="nav-group">平台管理</p>':'')+'<a class="nav-item nav-'+id+'" href="#'+id+'">'+icon(id)+'<span>'+title+'</span>'+(id==='updates'?'<i>NEW</i>':'')+'</a>').join('');
 const heading=(en,title,desc)=>'<header class="page-heading"><div><p class="eyebrow">'+en+'</p><h1>'+title+'</h1><p>'+desc+'</p></div><span class="badge muted">'+(preview?'本地界面预览':'已认证只读面板')+'</span></header>';
 const pending=(title,desc)=>'<div class="empty-state big-empty"><div class="empty-symbol">'+icon('baseline')+'</div><strong>'+title+'</strong><p>'+desc+'</p><span class="badge muted">待接入发布服务</span></div>';
 const module=(id,title,en,desc)=>'<a class="card module-card" href="#'+id+'"><div class="card-head"><span class="module-icon">'+icon(id)+'</span><span class="corner">↗</span></div><p class="eyebrow">'+en+'</p><h3>'+title+'</h3><p>'+desc+'</p><span class="module-state">'+(id==='baseline'?'从可信节点读取':id==='policy'?'固定安全策略 · v'+escapeHtml(policy.version):'发布能力待接入')+'</span></a>';
 return '<!doctype html><html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="theme-color" content="#090d16">'+(preview?'':'<meta http-equiv="refresh" content="30">')+'<title>玄武引擎 · Xuanwu 云安全平台</title><style>'+dashboardTheme+'</style></head><body><div class="xc-shell"><aside class="xc-sidebar"><a href="#overview" class="brand"><span class="brand-symbol">'+icon('baseline')+'</span><span><strong>玄武引擎</strong><small>XUANWU ENGINE</small></span></a><span class="platform-label">云安全平台</span><p class="nav-group">工作台</p><nav aria-label="玄武引擎功能">'+nav+'</nav><div class="sidebar-bottom"><span class="status-dot"></span><div><strong>铁幕安全的云端中枢</strong><small>可信连接 · 本地执行</small></div></div></aside><div class="xc-workspace"><header class="topbar"><span>玄武引擎 <span class="slash">/</span> 云安全控制台</span><div><span class="top-status">'+(preview?'UI PREVIEW':'READ ONLY')+'</span><a href="#connection" class="top-action">'+icon('connection')+'身份与连接</a></div></header>'+(preview?'<div class="preview-note"><span>界面预览</span>当前未连接生产云端，所有未知状态均保留；发布功能等待后续接入。</div>':'')+'<main class="xc-panels">'+
 '<section id="overview" class="xc-page default-page">'+heading('SECURITY OVERVIEW','云端安全总览','统一掌握铁幕终端、威胁规则与可信更新。')+'<section class="engine-hero card"><div class="hero-copy"><span class="hero-label"><span class="status-dot"></span>XUANWU · CLOUD DEFENSE ENGINE</span><h2>云端汇聚安全能力。<br>每一道铁幕，皆有依托<span>。</span></h2><p>病毒库、查杀策略与可信更新，在这里统一管理。<br>让每一次检测有依据，让每一次更新可追溯。</p><div class="hero-actions"><a class="button primary" href="#nodes">查看铁幕终端 <span>↗</span></a><a class="button secondary" href="#updates">更新发布中心</a></div><div class="hero-status">'+summary+'<span>根据终端有效报告评估</span></div></div><div class="engine-art" aria-hidden="true">'+core+'<span class="art-label">TRUST AT THE CORE</span></div></section><section class="stats"><article class="card stat"><span>已注册终端</span><strong>'+configured.length+'<small> 个</small></strong><p>身份已创建的业务节点</p></article><article class="card stat"><span>已认证连接</span><strong>'+connected.length+'<small> 个</small></strong><p>通过认证且报告有效</p></article><article class="card stat"><span>签名哈希规则</span><strong class="small-value">'+ruleVersion+'</strong><p>'+ (ruleReady?'已核验 · '+ruleCount+' 条特征':'等待有效签名规则')+'</p></article><article class="card stat"><span>安全策略版本</span><strong>v'+escapeHtml(policy.version)+'</strong><p>固定策略 · 本地受控执行</p></article></section><div class="section-heading"><h2>云端能力中心</h2><span>SECURITY CAPABILITIES</span></div><section class="modules">'+module('virus','病毒库中心','THREAT INTELLIGENCE','统一管理病毒特征与恶意文件规则。')+module('policy','查杀与策略','DETECTION & POLICY','从检查范围到处置边界，明确每一步。')+module('updates','铁幕更新发布','TRUSTED DELIVERY','程序、病毒库、规则，分别管理版本。')+module('baseline','可信基线','INTEGRITY BASELINE','对照可信发布，核验每一次文件变化。')+'</section><section class="overview-lower"><article class="card"><div class="card-head"><h2>铁幕终端接入</h2><a class="text-link" href="#nodes">全部终端 ↗</a></div><div class="endpoint-empty">'+icon('nodes')+'<div><strong>'+ (configured.length?'已注册 '+configured.length+' 个业务节点':'等待第一台铁幕终端')+'</strong><p>'+ (configured.length?'查看节点报告、完整性与环境检查状态。':'完成证书握手后，终端状态与安全报告将在此汇聚。')+'</p></div><a href="#connection" class="button secondary">对接指引</a></div></article><article class="card"><div class="card-head"><h2>最近安全事件</h2><a class="text-link" href="#events">查看全部 ↗</a></div><ul class="events compact">'+eventRows+'</ul></article></section></section>'+
 '<section id="nodes" class="xc-page">'+heading('ENDPOINT MANAGEMENT','铁幕终端','汇聚终端报告，核对文件、环境与身份状态。')+'<div class="section-heading"><h2>受保护节点</h2><a class="button primary" href="#connection">加密对接 ↗</a></div><section class="node-grid">'+nodeCards+'</section><div class="notice">节点上报反映本地检查结果；失联或过期时保留未知状态，不将其视为安全。</div></section>'+
 '<section id="virus" class="xc-page">'+heading('THREAT INTELLIGENCE','病毒库与哈希规则','展示实际验签结果；官方病毒库与哈希规则分别管理。')+'<section class="release-grid">'+ruleCard+'</section><article class="card"><div class="card-head"><h2>规则身份与来源</h2></div><dl class="details"><div><dt>载荷 SHA-256</dt><dd>'+ (ruleReady?escapeHtml(rules.payload_sha256):'—')+'</dd></div><div><dt>分发方式</dt><dd>双向证书 + 独立令牌；终端主动拉取</dd></div></dl><p>通过云端 Linux 菜单导入离线签名包，通过铁幕菜单拉取并验签。到期、错误签名与不兼容规则不会作为有效规则提供。</p></article><div class="notice">哈希规则命中保留证据和告警。官方 ClamAV 病毒库由铁幕 Linux 菜单独立更新，云端病毒库分发尚待验收。</div></section>'+
 '<section id="policy" class="xc-page">'+heading('DETECTION & RESPONSE','查杀与策略','检查策略、云端研判与本地处置，边界清晰。')+'<article class="card policy-banner"><div>'+icon('policy')+'<h2>当前安全策略 <span>v'+escapeHtml(policy.version)+'</span></h2></div><span class="badge muted">固定只读策略</span></article><section class="feature-grid"><article class="card"><h3>可信更新</h3><p>程序更新必须通过签名校验。</p><span class="badge ok">强制验签</span></article><article class="card"><h3>终端主动拉取</h3><p>策略由终端请求，云端不主动执行指令。</p><span class="badge ok">Pull-only</span></article><article class="card"><h3>本地受控执行</h3><p>云端不提供 SSH 或任意命令执行。</p><span class="badge ok">远程命令禁用</span></article></section><article class="card"><div class="card-head"><h2>查杀逻辑与策略编排</h2><span class="badge muted">编辑服务待接入</span></div><div class="strategy-flow"><div><b>01</b><strong>检测范围</strong><p>文件 · 容器 · 系统环境</p></div><div><b>02</b><strong>核验与研判</strong><p>特征匹配 · 基线比对</p></div><div><b>03</b><strong>受控处置</strong><p>告警 · 隔离 · 可信恢复</p></div><div><b>04</b><strong>结果追溯</strong><p>报告 · 证据 · 审计</p></div></div><div class="notice">当前面板展示流程设计。动态策略编辑与下发尚未开放。</div></article></section>'+
 '<section id="baseline" class="xc-page">'+heading('TRUST & INTEGRITY','可信基线','把正式程序摘要与节点上报放在同一处核验。')+'<section class="node-grid">'+requiredRoles.map(name=>'<article class="card"><div class="card-head"><h2>'+escapeHtml(label(name))+'</h2>'+badge(nodesMap[name]?.integrity?.state??'unconfigured')+'</div><div class="baseline-count"><strong>'+escapeHtml(nodesMap[name]?.baseline_files??'—')+'</strong><span>可信文件摘要</span></div><p>最近报告：'+time(nodesMap[name]?.last_report_at)+'</p><p class="muted">文件范围由注册时的可信基线确定。</p></article>').join('')+'</section><article class="card"><div class="card-head"><h2>恢复资源库</h2><span class="badge muted">待接入</span></div>'+pending('等待可信恢复资源','恢复包需要独立签名、版本核对与本地执行检查。')+'</article></section>'+
 '<section id="updates" class="xc-page">'+heading('TRUSTED RELEASE CENTER','更新发布','玄武引擎统一管理铁幕程序、病毒库和防护规则更新。')+'<section class="release-grid">'+ruleCard+releaseCard+[['病毒特征库','SIGNATURE DATABASE','扫描特征数据与来源版本']].map(([title,en,desc])=>'<article class="card release-card"><div class="release-icon">'+icon('updates')+'</div><p class="eyebrow">'+en+'</p><h3>'+title+'</h3><p>'+desc+'</p><dl class="details"><div><dt>最新发布</dt><dd>—</dd></div><div><dt>验签状态</dt><dd>尚无发布包</dd></div></dl><span class="badge muted">发布服务待接入</span></article>').join('')+'</section><article class="card"><div class="card-head"><h2>程序更新操作</h2><span class="badge muted">管理员本机执行</span></div><p>玄武运行 xuanwu，选择“导入正式签名程序包”；铁幕运行 ironcurtain，选择“从玄武验签下载并更新铁幕程序”。</p><p class="muted">升级沿用健康检查和事务回滚；网页不触发程序安装。</p></article><div class="notice">页面不会从未核验的来源安装程序。软件更新、规则更新和病毒库更新分别记录版本。</div></section>'+
 '<section id="events" class="xc-page">'+heading('SECURITY AUDIT','安全事件','保留认证、文件核验与终端检查的真实记录。')+'<article class="card"><div class="card-head"><h2>事件时间线</h2><span class="badge muted">'+(status.events??[]).length+' 条记录</span></div><ul class="events">'+eventRows+'</ul></article></section>'+
 '<section id="connection" class="xc-page">'+heading('IDENTITY & CONNECTION','加密对接','证书握手与独立凭据，共同确定每一个终端身份。')+'<section class="connection-grid"><article class="card"><div class="card-head"><h2>首次对接进度</h2>'+badge(fullyConnected?'ready':'partial')+'</div><ol class="guide-list">'+guide+'</ol><div class="notice">'+escapeHtml(nextAction)+'</div></article><article class="card"><div class="card-head"><h2>身份与证书</h2><span class="badge muted">只读查看</span></div>'+roleRows+'<div class="notice">凭据在 Linux 管理菜单中创建与轮换。面板不显示私钥或令牌。</div></article></section><section class="feature-grid"><article class="card"><h3>双向证书认证</h3><p>终端与云端核对证书身份，拒绝未知节点。</p></article><article class="card"><h3>独立凭据与轮换</h3><p>各角色使用独立凭据，避免共享全部权限。</p></article><article class="card"><h3>本地执行边界</h3><p>云端无 SSH、Docker Socket 或远程命令能力；处置由业务节点本地执行。</p></article></section></section>'+
 '</main><footer class="xc-footer"><span>XUANWU ENGINE <i>·</i> 玄武引擎云安全平台</span><span>'+ (preview?'本地界面预览 · 无生产连接':time(status.generated_at)+' · 30 秒刷新')+'</span></footer></div></div></body></html>';
}
